### ISSUE TITLE
SMCProcessor and SMCSuperIO absence inside the VirtualSMC

### ISSUE THREAD

**Issue by Nick-IV** [vulgo/ga-h97n-wifi-hackintosh#29]
Hi Vulgo,
VirtualSMC version in your repo do not contain SMCProcessor and SMCSuperIO kexts inside.
Actually the origin VirtualSMC from GitHub do not contain they too.
Probably you need to add these two into Kexts folder and fix path in config.plist.
Regards,
Nick.

**Comment by vulgo** [comment]
Thanks @Nick-IV I've added the missing kexts and made a new release of 0.8.8, thanks very much for this

**Comment by vulgo** [comment]
I think if you have a desktop and you want the SMC to read/write temperatures fan speeds etc. this is a common configuration of "plugins". The other plugins look to me to be useful on laptops. It's nice to have the flexibility plugins (e.g. no plugins) and writing and building the releases it might be convenient. I think building fewer kexts one might cover all use cases (as in use just one) otherwise there's always the chance I'll be careless and do something fatal updating the right combination of SMC kexts...
